// Test GET and POST requests here

GET api.openweathermap.org/data/2.5/weather?q=Boulder,co,usa&appid= HTTP/1.1
# content-type: application/json

# {
#     "name": "sample",
#     "time": "Wed, 21 Oct 2015 18:27:50 GMT"
# }

// Example of API call:
// http://api.openweathermap.org/data/2.5/weather?q=London,uk&APPID=f3b3c41207f26b2aa5ecc7927bdb80fa